const data = {
  'NYP': {
    'school': 'NYP',
    'country': 'SG',
    'name': 'Nanyang Polytechnic',
    'image': '/images/school-logos/Nanyang_Polytechnic_Square.jpg',
    'grades': {
      'DIST': 4.0,
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  'NP': {
    'school': 'NP',
    'country': 'SG',
    'name': 'Ngee Ann Polytechnic',
    'image': '/images/school-logos/NgeeAnn_Polytechnic_Square.jpg',
    'grades': {
      'AD*': 4.0,
      'A+': 4.0,
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
      'PM': -1,
    },
  },
  'SP': {
    'school': 'SP',
    'country': 'SG',
    'name': 'Singapore Polytechnic',
    'image': '/images/school-logos/Singapore_Polytechnic_Square.jpg',
    'grades': {
      'DIST': 4.0,
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'D-': 0.5,
      'P': 0.5,
      'F': 0,
      'ABS': 0,
    },
  },
  'RP': {
    'school': 'RP',
    'country': 'SG',
    'name': 'Republic Polytechnic',
    'image': '/images/school-logos/Republic_Polytechnic_Square.jpg',
    'grades': {
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.02,
      'D+': 1.5,
      'D': 1.0,
      'E': 0.5,
      'F': 0,
    },
  },
  'TP': {
    'school': 'TP',
    'country': 'SG',
    'name': 'Temasek Polytechnic',
    'image': '/images/school-logos/Temasek_Polytechnic_Square.jpg',
    'grades': {
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'E': 0.5,
      'F': 0,
    },
  },
  'NUS': {
    'school': 'NUS',
    'country': 'SG',
    'name': 'National University of Singapore',
    'image': '/images/school-logos/National_University_of_Singapore_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  'SIT': {
    'school': 'SIT',
    'country': 'SG',
    'name': 'Singapore Institute of Technology',
    'image': '/images/school-logos/Singapore_Institute_of_Technology_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  'NTU': {
    'school': 'NTU',
    'country': 'SG',
    'name': 'Nanyang Technological University',
    'image': '/images/school-logos/Nanyang_Technological_University_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  'SUSS': {
    'school': 'SUSS',
    'country': 'SG',
    'name': 'Singapore University of Social Sciences',
    'image': '/images/school-logos/Singapore_University_of_Social_Sciences_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  'SUTD': {
    'school': 'SUTD',
    'country': 'SG',
    'name': 'Singapore University of Technology and Design',
    'image': '/images/school-logos/Singapore_University_of_Technology_and_Design_Square.jpg',
    'grades': {
      'A+': 5.0,
      'B': 4.0,
      'C': 3.0,
      'D': 2.0,
      'F': 0,
    },
  },
  'SMU': {
    'school': 'SMU',
    'country': 'SG',
    'name': 'Singapore Management University',
    'image': '/images/school-logos/Singapore_Management_University_Square.jpg',
    'grades': {
      'A+': 4.3,
      'A': 4.0,
      'A-': 3.7,
      'B+': 3.3,
      'B': 3.0,
      'B-': 2.7,
      'C+': 2.4,
      'C': 2.0,
      'C-': 1.7,
      'D+': 1.3,
      'D': 1.0,
      'F': 0,
    },
  },
} as const;

export default data;
