const data = [
  {
    'school': 'NYP',
    'country': 'SG',
    'name': 'Nanyang Polytechnic',
    'image': '/images/school-logos/Nanyang_Polytechnic_Square.jpg',
    'grades': {
      'DIST': 4.0,
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'NP',
    'country': 'SG',
    'name': 'Ngee Ann Polytechnic',
    'image': '/images/school-logos/NgeeAnn_Polytechnic_Square.jpg',
    'grades': {
      'AD*': 4.0,
      'A+': 4.0,
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
      'PM': -1,
    },
  },
  {
    'school': 'SP',
    'country': 'SG',
    'name': 'Singapore Polytechnic',
    'image': '/images/school-logos/Singapore_Polytechnic_Square.jpg',
    'grades': {
      'DIST': 4.0,
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'D-': 0.5,
      'P': 0.5,
      'F': 0,
      'ABS': 0,
    },
  },
  {
    'school': 'RP',
    'country': 'SG',
    'name': 'Republic Polytechnic',
    'image': '/images/school-logos/Republic_Polytechnic_Square.jpg',
    'grades': {
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'E': 0.5,
      'F': 0,
    },
  },
  {
    'school': 'TP',
    'country': 'SG',
    'name': 'Temasek Polytechnic',
    'image': '/images/school-logos/Temasek_Polytechnic_Square.jpg',
    'grades': {
      'A': 4.0,
      'B+': 3.5,
      'B': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'E': 0.5,
      'F': 0,
    },
  },
  {
    'school': 'NUS',
    'country': 'SG',
    'name': 'National University of Singapore',
    'image': '/images/school-logos/NUS_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'SIT',
    'country': 'SG',
    'name': 'Singapore Institute of Technology',
    'image': '/images/school-logos/Singapore_Institute_of_Technology_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'NTU',
    'country': 'SG',
    'name': 'Nanyang Technological University',
    'image': '/images/school-logos/NTU_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'SUSS',
    'country': 'SG',
    'name': 'Singapore University of Social Sciences',
    'image': '/images/school-logos/SUSS_Square.jpg',
    'grades': {
      'A+': 5.0,
      'A': 5.0,
      'A-': 4.5,
      'B+': 4.0,
      'B': 3.5,
      'B-': 3.0,
      'C+': 2.5,
      'C': 2.0,
      'D+': 1.5,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'SUTD',
    'country': 'SG',
    'name': 'Singapore University of Technology and Design',
    'image': '/images/school-logos/SUTD_Square.jpg',
    'grades': {
      'A+': 5.0,
      'B': 4.0,
      'C': 3.0,
      'D': 2.0,
      'F': 0,
    },
  },
  {
    'school': 'SMU',
    'country': 'SG',
    'name': 'Singapore Management University',
    'image': '/images/school-logos/SMU_Square.jpg',
    'grades': {
      'A+': 4.3,
      'A': 4.0,
      'A-': 3.7,
      'B+': 3.3,
      'B': 3.0,
      'B-': 2.7,
      'C+': 2.4,
      'C': 2.0,
      'C-': 1.7,
      'D+': 1.3,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'DP',
    'country': 'SG',
    'name': 'DigiPen Institute of Technology, Singapore',
    'image': '/images/school-logos/DigiPen_Square.jpg',
    'grades': {
      'A': 4.0,
      'A-': 3.7,
      'B+': 3.3,
      'B': 3.0,
      'B-': 2.7,
      'C+': 2.3,
      'C': 2.0,
      'C-': 1.7,
      'D': 1.0,
      'F': 0,
    },
  },
  {
    'school': 'TUM',
    'country': 'SG',
    'name': 'Technical University of Munich Asia',
    'filename': 'TUM',
    'image': '/images/school-logos/TUM_Square.jpg',
    'grades': {
      '5.0': 5.0,
      '4.7': 4.7,
      '4.3': 4.3,
      '4.0': 4.0,
      '3.7': 3.7,
      '3.3': 3.3,
      '3.0': 3.0,
      '2.7': 2.7,
      '2.3': 2.3,
      '2.0': 2.0,
      '1.7': 1.7,
      '1.3': 1.3,
      '1.0': 1.0,
    },
  },
] as const;

export default data;
